# Generated by Django 5.1.5 on 2026-10-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
