# Generated by Django 5.1.5 on 2026-10-09 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_explicit_nullable_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(condition=models.Q(('month__isnull', True), ('year__isnull', False)), fields=('user', 'year'), name='unique_goal_annual_period'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(condition=models.Q(('month__isnull', False), ('year__isnull', False)), fields=('user', 'year', 'month'), name='unique_goal_monthly_period'),
        ),
    ]
